services:
  psql-db:
    image: postgis/postgis
    container_name: psql-db
    env_file: ./conf/dev.env
    ports:
      # bind host port 5431 to docker container exposed port 5432
      - "5431:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    healthcheck:
      # used in flask container depends_on condition to wait for the DB to be ready
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 20s
      retries: 5
volumes:
  # to persist the database tables
  db-volume:

